---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  values:
    global:
      logging:
        level: default:debug
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
  components:
    pilot:
      hub: istio
      tag: 1.14.4
      k8s:
        resources:
          requests:
            cpu: 250m # override from default 500m
            memory: 1024Mi # ... default 2048Mi
