---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  values:
    global:
      logging:
        level: default:debug
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
      proxyStatsMatcher:
        inclusionPrefixes:
          - thrift
          - dubbo
          - kafka
          - meta_protocol
        inclusionRegexps:
          - .*dubbo.*
          - .*thrift.*
          - .*kafka.*
          - .*zookeeper.*
          - .*meta_protocol.*
      tracing:
        sampling: 100
        zipkin:
          address: zipkin.istio-system:9411
  components:
    pilot:
      hub: istio
      tag: 1.15.6
      k8s:
        resources:
          requests:
            cpu: 250m # override from default 500m
            memory: 1024Mi # ... default 2048Mi
